/* AUTO-GENERATED by scripts/update_xauusd.py. Do not hand-edit. */
window.XAUUSD_DATA = {
  "meta": {
    "pipelineVersion": "2.0.0",
    "generatedAt": "2026-10-08T10:40:51+08:00",
    "timezone": "Asia/Kuala_Lumpur",
    "cadence": "daily",
    "expectedUpdateLocal": "07:10",
    "staleAfterHours": 30,
    "verified": true,
    "seed": false,
    "sourceStatus": {
      "xau": {
        "ok": true,
        "label": "Twelve Data XAU/USD",
        "detail": "latest daily bar 2026-10-08",
        "timestamp": "2026-10-08T10:40:51+08:00"
      },
      "dxy": {
        "ok": false,
        "label": "Twelve Data DXY",
        "detail": "No exact/confirmed DXY symbol found",
        "timestamp": "2026-10-08T10:40:51+08:00"
      },
      "brent": {
        "ok": false,
        "label": "Twelve Data Brent",
        "detail": "404 Client Error: Not Found for url: https://api.twelvedata.com/time_series?symbol=XBR%2FUSD&interval=1day&outputsize=3&order=DESC&timezone=UTC&apikey=[REDACTED]",
        "timestamp": "2026-10-08T10:41:00+08:00"
      },
      "us10y": {
        "ok": true,
        "label": "FRED DGS10",
        "detail": "latest 2026-10-06",
        "timestamp": "2026-10-08T10:41:01+08:00"
      },
      "news": {
        "ok": true,
        "label": "NewsAPI",
        "detail": "1 relevant recent items",
        "timestamp": "2026-10-08T10:41:01+08:00"
      },
      "fedSpeeches": {
        "ok": true,
        "label": "Federal Reserve speeches",
        "detail": "6 official listings",
        "timestamp": "2026-10-08T10:41:01+08:00"
      }
    },
    "warnings": [
      "DXY unavailable; dashboard shows — rather than substituting an unverified dollar index.",
      "Brent unavailable for this run."
    ]
  },
  "updated": "2026-10-08 10:40 MYT",
  "session": "Daily verified snapshot · sourced data + labelled heuristic overlays",
  "price": {
    "spot": 4141.64,
    "change": 41.1,
    "changePct": 1.0,
    "dayRange": "4,100.43 - 4,142.51",
    "monthPct": -5.38,
    "yearPct": -4.02,
    "ath": null,
    "note": "Latest provider daily bar: 2026-10-08; rolling history used: 370 bars",
    "latestDailyClose": 4141.64,
    "priceType": "DAILY_CLOSE",
    "rollingHigh": 5597.23,
    "rollingWindowBars": 370,
    "providerBarTime": "2026-10-08"
  },
  "macro": [
    {
      "label": "DXY",
      "value": "—",
      "delta": "unavailable",
      "tone": "",
      "note": "Provider symbol not confirmed"
    },
    {
      "label": "US 10Y",
      "value": "5.270%",
      "delta": "-4.0 bp",
      "tone": "good",
      "note": "FRED DGS10 · 2026-10-06"
    },
    {
      "label": "Brent",
      "value": "—",
      "delta": "unavailable",
      "tone": "",
      "note": "Provider symbol not confirmed"
    }
  ],
  "sentiment": {
    "bias": "UPWARD",
    "goldTone": "BULLISH",
    "score": 0.394,
    "confidence": 69,
    "summary": "Mechanical daily pressure model using sourced USD/yield moves plus a small observed XAU-momentum term. It is not a forecast or trade instruction.",
    "netSpeechSignal": "UP",
    "netSpeechPct": 0.0,
    "netNote": "Direction only. No fabricated percentage impact is assigned to headlines or speeches."
  },
  "model": {
    "base": 0.0,
    "formula": "dailyPressure = weighted(ΔDXY, ΔUS10Y, observed ΔXAU)",
    "note": "Transparent heuristic over sourced daily data. No headline/speech percentage impact is fabricated.",
    "weights": [
      {
        "k": "DXY daily move",
        "v": 0.45
      },
      {
        "k": "US 10Y daily move",
        "v": 0.45
      },
      {
        "k": "Observed XAU momentum",
        "v": 0.1
      }
    ],
    "strength": [
      {
        "k": "Source available",
        "v": 1.0
      },
      {
        "k": "Source unavailable",
        "v": 0.0
      }
    ],
    "surprise": [
      {
        "k": "Not auto-estimated",
        "v": 0.0
      }
    ]
  },
  "news": [
    {
      "time": "2026-10-07 01:58 UTC",
      "title": "Gold flat as focus turns to Fed minutes",
      "summary": "Gold prices remained steady as market participants look forward to insights from the Federal Reserve's upcoming meeting minutes. Spot gold hovered at $4,159.62 per ounce, while December futures were valued at $4,187.30. Amid ongoing inflation and recent slugg…",
      "source": "The Times of India",
      "url": "https://economictimes.indiatimes.com/markets/commodities/news/gold-flat-as-focus-turns-to-fed-minutes/articleshow/134753704.cms",
      "impact": "neutral",
      "signal": "NEUTRAL",
      "impactPct": null
    }
  ],
  "speakers": [
    {
      "name": "Modernizing the Regulatory and Supervisory Landscape",
      "role": "Federal Reserve speaker",
      "side": "neutral",
      "signal": "NEUTRAL",
      "quote": "Modernizing the Regulatory and Supervisory Landscape Watch Live Vice Chair for Supervision Michelle W. Bowman At the 2026 Community Banking Research Conference, sponsored by the Federal Reserve System, the Conference of State Bank Supervisors, and the Federal ",
      "impact": "Official Fed speech listing; stance is not automatically inferred.",
      "date": "2026",
      "source": "Federal Reserve",
      "url": "https://www.federalreserve.gov/newsevents/speech/bowman20261006a.htm",
      "w": 0.0,
      "s": 0.0,
      "f": 0.0,
      "impactPct": 0.0
    },
    {
      "name": "Modernizing Financial Regulation: Initial Observations from eSLR",
      "role": "Federal Reserve speaker",
      "side": "neutral",
      "signal": "NEUTRAL",
      "quote": "Modernizing Financial Regulation: Initial Observations from eSLR Watch Live Vice Chair for Supervision Michelle W. Bowman At the Atlantic Council 2026 CEO & Senior Management Summit, Washington, D.C.",
      "impact": "Official Fed speech listing; stance is not automatically inferred.",
      "date": "2026",
      "source": "Federal Reserve",
      "url": "https://www.federalreserve.gov/newsevents/speech/bowman20261001a.htm",
      "w": 0.0,
      "s": 0.0,
      "f": 0.0,
      "impactPct": 0.0
    },
    {
      "name": "The U.S. Economy and Monetary Policy",
      "role": "Federal Reserve speaker",
      "side": "neutral",
      "signal": "NEUTRAL",
      "quote": "The U.S. Economy and Monetary Policy Watch Live Vice Chair Philip N. Jefferson At the Darden School of Business, University of Virginia, Charlottesville, Virginia",
      "impact": "Official Fed speech listing; stance is not automatically inferred.",
      "date": "2026",
      "source": "Federal Reserve",
      "url": "https://www.federalreserve.gov/newsevents/speech/jefferson20261001a.htm",
      "w": 0.0,
      "s": 0.0,
      "f": 0.0,
      "impactPct": 0.0
    },
    {
      "name": "The Data Version of Godzilla versus Kong: FRED Takes on AI",
      "role": "Federal Reserve speaker",
      "side": "neutral",
      "signal": "NEUTRAL",
      "quote": "The Data Version of Godzilla versus Kong: FRED Takes on AI Watch Live Governor Christopher J. Waller At \"Navigating Trust, AI and Storytelling in a World of Data,\" FRED Con 2026, Federal Reserve Bank of St. Louis, St. Louis, Missouri",
      "impact": "Official Fed speech listing; stance is not automatically inferred.",
      "date": "2026",
      "source": "Federal Reserve",
      "url": "https://www.federalreserve.gov/newsevents/speech/waller20261001a.htm",
      "w": 0.0,
      "s": 0.0,
      "f": 0.0,
      "impactPct": 0.0
    },
    {
      "name": "The Dual Mandate in Rural America",
      "role": "Federal Reserve speaker",
      "side": "neutral",
      "signal": "NEUTRAL",
      "quote": "The Dual Mandate in Rural America Governor Lisa D. Cook At the 2026 Investing in Rural America Conference, Federal Reserve Bank of Richmond, Asheville, North Carolina",
      "impact": "Official Fed speech listing; stance is not automatically inferred.",
      "date": "2026",
      "source": "Federal Reserve",
      "url": "https://www.federalreserve.gov/newsevents/speech/cook20260930a.htm",
      "w": 0.0,
      "s": 0.0,
      "f": 0.0,
      "impactPct": 0.0
    },
    {
      "name": "Payments in the Age of AI Agents",
      "role": "Federal Reserve speaker",
      "side": "neutral",
      "signal": "NEUTRAL",
      "quote": "Payments in the Age of AI Agents Watch Live Governor Christopher J. Waller At Sibos 2026, Miami, Florida",
      "impact": "Official Fed speech listing; stance is not automatically inferred.",
      "date": "2026",
      "source": "Federal Reserve",
      "url": "https://www.federalreserve.gov/newsevents/speech/waller20260928a.htm",
      "w": 0.0,
      "s": 0.0,
      "f": 0.0,
      "impactPct": 0.0
    }
  ],
  "levels": {
    "resistance": [
      4159.65,
      4218.78,
      4267.74,
      4384.53
    ],
    "support": [
      4061.73,
      4051.57,
      4002.61,
      3943.49
    ],
    "note": "Classic pivot levels from previous daily OHLC plus recent 20-day extreme; mechanical, not guarantees."
  },
  "calendar": [],
  "pressure": [
    {
      "label": "US 10Y daily move",
      "level": "-4.0 bp",
      "w": 33,
      "dir": "up"
    },
    {
      "label": "Observed XAU momentum",
      "level": "+1.00%",
      "w": 66,
      "dir": "up"
    }
  ],
  "priceSeries": {
    "label": "XAU/USD daily close (Twelve Data)",
    "unit": "USD / troy oz",
    "yMin": 4078.25,
    "yMax": 4308.49,
    "points": [
      {
        "x": "2026-09-26",
        "y": 4286.21
      },
      {
        "x": "2026-09-27",
        "y": 4286.21
      },
      {
        "x": "2026-09-28",
        "y": 4115.08
      },
      {
        "x": "2026-09-29",
        "y": 4182.0
      },
      {
        "x": "2026-09-30",
        "y": 4156.46
      },
      {
        "x": "2026-10-01",
        "y": 4177.45
      },
      {
        "x": "2026-10-02",
        "y": 4141.53
      },
      {
        "x": "2026-10-03",
        "y": 4137.61
      },
      {
        "x": "2026-10-04",
        "y": 4137.63
      },
      {
        "x": "2026-10-04",
        "y": 4137.51
      },
      {
        "x": "2026-10-05",
        "y": 4141.05
      },
      {
        "x": "2026-10-06",
        "y": 4169.39
      },
      {
        "x": "2026-10-07",
        "y": 4100.53
      },
      {
        "x": "2026-10-08",
        "y": 4141.64
      }
    ]
  },
  "macroSeries": {
    "label": "DXY unavailable",
    "unit": "index",
    "yMin": 0,
    "yMax": 1,
    "points": [
      {
        "x": "2026-10-08",
        "y": 0
      }
    ]
  },
  "oddsSeries": {
    "label": "DXY unavailable",
    "unit": "index",
    "yMin": 0,
    "yMax": 1,
    "points": [
      {
        "x": "2026-10-08",
        "y": 0
      }
    ]
  },
  "sources": [
    "Twelve Data — XAU/USD daily market data",
    "Federal Reserve — official speech listings",
    "FRED — DGS10 US 10-Year Treasury Constant Maturity Rate",
    "NewsAPI — recent gold/macro headlines"
  ]
};
