/* AUTO-GENERATED by scripts/update_xauusd.py. Do not hand-edit. */
window.XAUUSD_DATA = {
  "meta": {
    "pipelineVersion": "2.0.0",
    "generatedAt": "2026-10-02T10:12:10+08:00",
    "timezone": "Asia/Kuala_Lumpur",
    "cadence": "daily",
    "expectedUpdateLocal": "07:10",
    "staleAfterHours": 30,
    "verified": true,
    "seed": false,
    "sourceStatus": {
      "xau": {
        "ok": true,
        "label": "Twelve Data XAU/USD",
        "detail": "latest daily bar 2026-10-02",
        "timestamp": "2026-10-02T10:12:10+08:00"
      },
      "dxy": {
        "ok": false,
        "label": "Twelve Data DXY",
        "detail": "No exact/confirmed DXY symbol found",
        "timestamp": "2026-10-02T10:12:10+08:00"
      },
      "brent": {
        "ok": false,
        "label": "Twelve Data Brent",
        "detail": "404 Client Error: Not Found for url: https://api.twelvedata.com/time_series?symbol=XBR%2FUSD&interval=1day&outputsize=3&order=DESC&timezone=UTC&apikey=[REDACTED]",
        "timestamp": "2026-10-02T10:12:18+08:00"
      },
      "us10y": {
        "ok": true,
        "label": "FRED DGS10",
        "detail": "latest 2026-09-30",
        "timestamp": "2026-10-02T10:12:19+08:00"
      },
      "news": {
        "ok": true,
        "label": "NewsAPI",
        "detail": "2 relevant recent items",
        "timestamp": "2026-10-02T10:12:19+08:00"
      },
      "fedSpeeches": {
        "ok": true,
        "label": "Federal Reserve speeches",
        "detail": "6 official listings",
        "timestamp": "2026-10-02T10:12:19+08:00"
      }
    },
    "warnings": [
      "DXY unavailable; dashboard shows — rather than substituting an unverified dollar index.",
      "Brent unavailable for this run."
    ]
  },
  "updated": "2026-10-02 10:12 MYT",
  "session": "Daily verified snapshot · sourced data + labelled heuristic overlays",
  "price": {
    "spot": 4156.35,
    "change": -21.1,
    "changePct": -0.51,
    "dayRange": "4,134.45 - 4,183.58",
    "monthPct": -4.43,
    "yearPct": -3.68,
    "ath": null,
    "note": "Latest provider daily bar: 2026-10-02; rolling history used: 370 bars",
    "latestDailyClose": 4156.35,
    "priceType": "DAILY_CLOSE",
    "rollingHigh": 5597.23,
    "rollingWindowBars": 370,
    "providerBarTime": "2026-10-02"
  },
  "macro": [
    {
      "label": "DXY",
      "value": "—",
      "delta": "unavailable",
      "tone": "",
      "note": "Provider symbol not confirmed"
    },
    {
      "label": "US 10Y",
      "value": "5.290%",
      "delta": "+3.0 bp",
      "tone": "bad",
      "note": "FRED DGS10 · 2026-09-30"
    },
    {
      "label": "Brent",
      "value": "—",
      "delta": "unavailable",
      "tone": "",
      "note": "Provider symbol not confirmed"
    }
  ],
  "sentiment": {
    "bias": "DOWNWARD",
    "goldTone": "BEARISH",
    "score": -0.266,
    "confidence": 69,
    "summary": "Mechanical daily pressure model using sourced USD/yield moves plus a small observed XAU-momentum term. It is not a forecast or trade instruction.",
    "netSpeechSignal": "DOWN",
    "netSpeechPct": 0.0,
    "netNote": "Direction only. No fabricated percentage impact is assigned to headlines or speeches."
  },
  "model": {
    "base": 0.0,
    "formula": "dailyPressure = weighted(ΔDXY, ΔUS10Y, observed ΔXAU)",
    "note": "Transparent heuristic over sourced daily data. No headline/speech percentage impact is fabricated.",
    "weights": [
      {
        "k": "DXY daily move",
        "v": 0.45
      },
      {
        "k": "US 10Y daily move",
        "v": 0.45
      },
      {
        "k": "Observed XAU momentum",
        "v": 0.1
      }
    ],
    "strength": [
      {
        "k": "Source available",
        "v": 1.0
      },
      {
        "k": "Source unavailable",
        "v": 0.0
      }
    ],
    "surprise": [
      {
        "k": "Not auto-estimated",
        "v": 0.0
      }
    ]
  },
  "news": [
    {
      "time": "2026-10-01 02:11 UTC",
      "title": "Gold prices flat ahead of US jobs data",
      "summary": "As Asia's trading day commenced, gold prices remained steady while market participants awaited the critical US jobs data release. This information is pivotal for deciphering the Federal Reserve's future interest rate moves. The latest inflation statistics fro…",
      "source": "The Times of India",
      "url": "https://economictimes.indiatimes.com/markets/commodities/news/gold-prices-flat-ahead-of-us-jobs-data/articleshow/134606175.cms",
      "impact": "neutral",
      "signal": "NEUTRAL",
      "impactPct": null
    },
    {
      "time": "2026-10-01 01:32 UTC",
      "title": "Yields, dollar hold key to gold, silver trajectory in H2FY27: Apurva Seth",
      "summary": "Gold and silver have corrected sharply since April, falling 11 per cent and 19 per cent, respectively, in USD terms.",
      "source": "Business Standard",
      "url": "https://www.business-standard.com/markets/commodities/yields-dollar-hold-key-to-gold-silver-trajectory-in-h2fy27-apurva-seth-126093000772_1.html",
      "impact": "neutral",
      "signal": "NEUTRAL",
      "impactPct": null
    }
  ],
  "speakers": [
    {
      "name": "Modernizing Financial Regulation: Initial Observations from eSLR",
      "role": "Federal Reserve speaker",
      "side": "neutral",
      "signal": "NEUTRAL",
      "quote": "Modernizing Financial Regulation: Initial Observations from eSLR Watch Live Vice Chair for Supervision Michelle W. Bowman At the Atlantic Council 2026 CEO & Senior Management Summit, Washington, D.C.",
      "impact": "Official Fed speech listing; stance is not automatically inferred.",
      "date": "2026",
      "source": "Federal Reserve",
      "url": "https://www.federalreserve.gov/newsevents/speech/bowman20261001a.htm",
      "w": 0.0,
      "s": 0.0,
      "f": 0.0,
      "impactPct": 0.0
    },
    {
      "name": "The U.S. Economy and Monetary Policy",
      "role": "Federal Reserve speaker",
      "side": "neutral",
      "signal": "NEUTRAL",
      "quote": "The U.S. Economy and Monetary Policy Watch Live Vice Chair Philip N. Jefferson At the Darden School of Business, University of Virginia, Charlottesville, Virginia",
      "impact": "Official Fed speech listing; stance is not automatically inferred.",
      "date": "2026",
      "source": "Federal Reserve",
      "url": "https://www.federalreserve.gov/newsevents/speech/jefferson20261001a.htm",
      "w": 0.0,
      "s": 0.0,
      "f": 0.0,
      "impactPct": 0.0
    },
    {
      "name": "The Data Version of Godzilla versus Kong: FRED Takes on AI",
      "role": "Federal Reserve speaker",
      "side": "neutral",
      "signal": "NEUTRAL",
      "quote": "The Data Version of Godzilla versus Kong: FRED Takes on AI Watch Live Governor Christopher J. Waller At \"Navigating Trust, AI and Storytelling in a World of Data,\" FRED Con 2026, Federal Reserve Bank of St. Louis, St. Louis, Missouri",
      "impact": "Official Fed speech listing; stance is not automatically inferred.",
      "date": "2026",
      "source": "Federal Reserve",
      "url": "https://www.federalreserve.gov/newsevents/speech/waller20261001a.htm",
      "w": 0.0,
      "s": 0.0,
      "f": 0.0,
      "impactPct": 0.0
    },
    {
      "name": "The Dual Mandate in Rural America",
      "role": "Federal Reserve speaker",
      "side": "neutral",
      "signal": "NEUTRAL",
      "quote": "The Dual Mandate in Rural America Governor Lisa D. Cook At the 2026 Investing in Rural America Conference, Federal Reserve Bank of Richmond, Asheville, North Carolina",
      "impact": "Official Fed speech listing; stance is not automatically inferred.",
      "date": "2026",
      "source": "Federal Reserve",
      "url": "https://www.federalreserve.gov/newsevents/speech/cook20260930a.htm",
      "w": 0.0,
      "s": 0.0,
      "f": 0.0,
      "impactPct": 0.0
    },
    {
      "name": "Payments in the Age of AI Agents",
      "role": "Federal Reserve speaker",
      "side": "neutral",
      "signal": "NEUTRAL",
      "quote": "Payments in the Age of AI Agents Watch Live Governor Christopher J. Waller At Sibos 2026, Miami, Florida",
      "impact": "Official Fed speech listing; stance is not automatically inferred.",
      "date": "2026",
      "source": "Federal Reserve",
      "url": "https://www.federalreserve.gov/newsevents/speech/waller20260928a.htm",
      "w": 0.0,
      "s": 0.0,
      "f": 0.0,
      "impactPct": 0.0
    },
    {
      "name": "Economic Conditions and Monetary Policy",
      "role": "Federal Reserve speaker",
      "side": "neutral",
      "signal": "NEUTRAL",
      "quote": "Economic Conditions and Monetary Policy Watch Live Governor Michael S. Barr At the Detroit Economic Club, Detroit, Michigan",
      "impact": "Official Fed speech listing; stance is not automatically inferred.",
      "date": "2026",
      "source": "Federal Reserve",
      "url": "https://www.federalreserve.gov/newsevents/speech/barr20260929a.htm",
      "w": 0.0,
      "s": 0.0,
      "f": 0.0,
      "impactPct": 0.0
    }
  ],
  "levels": {
    "resistance": [
      4200.05,
      4222.66,
      4252.79,
      4399.22
    ],
    "support": [
      4147.31,
      4117.17,
      4111.8,
      4094.57
    ],
    "note": "Classic pivot levels from previous daily OHLC plus recent 20-day extreme; mechanical, not guarantees."
  },
  "calendar": [],
  "pressure": [
    {
      "label": "US 10Y daily move",
      "level": "+3.0 bp",
      "w": 25,
      "dir": "down"
    },
    {
      "label": "Observed XAU momentum",
      "level": "-0.51%",
      "w": 33,
      "dir": "down"
    }
  ],
  "priceSeries": {
    "label": "XAU/USD daily close (Twelve Data)",
    "unit": "USD / troy oz",
    "yMin": 4083.27,
    "yMax": 4411.94,
    "points": [
      {
        "x": "2026-09-19",
        "y": 4380.13
      },
      {
        "x": "2026-09-20",
        "y": 4380.13
      },
      {
        "x": "2026-09-21",
        "y": 4343.81
      },
      {
        "x": "2026-09-22",
        "y": 4357.68
      },
      {
        "x": "2026-09-23",
        "y": 4286.97
      },
      {
        "x": "2026-09-24",
        "y": 4275.28
      },
      {
        "x": "2026-09-25",
        "y": 4286.74
      },
      {
        "x": "2026-09-26",
        "y": 4286.21
      },
      {
        "x": "2026-09-27",
        "y": 4286.21
      },
      {
        "x": "2026-09-28",
        "y": 4115.08
      },
      {
        "x": "2026-09-29",
        "y": 4182.0
      },
      {
        "x": "2026-09-30",
        "y": 4156.46
      },
      {
        "x": "2026-10-01",
        "y": 4177.45
      },
      {
        "x": "2026-10-02",
        "y": 4156.35
      }
    ]
  },
  "macroSeries": {
    "label": "DXY unavailable",
    "unit": "index",
    "yMin": 0,
    "yMax": 1,
    "points": [
      {
        "x": "2026-10-02",
        "y": 0
      }
    ]
  },
  "oddsSeries": {
    "label": "DXY unavailable",
    "unit": "index",
    "yMin": 0,
    "yMax": 1,
    "points": [
      {
        "x": "2026-10-02",
        "y": 0
      }
    ]
  },
  "sources": [
    "Twelve Data — XAU/USD daily market data",
    "Federal Reserve — official speech listings",
    "FRED — DGS10 US 10-Year Treasury Constant Maturity Rate",
    "NewsAPI — recent gold/macro headlines"
  ]
};
