/* AUTO-GENERATED by scripts/update_xauusd.py. Do not hand-edit. */
window.XAUUSD_DATA = {
  "meta": {
    "pipelineVersion": "2.0.0",
    "generatedAt": "2026-09-29T10:34:00+08:00",
    "timezone": "Asia/Kuala_Lumpur",
    "cadence": "daily",
    "expectedUpdateLocal": "07:10",
    "staleAfterHours": 30,
    "verified": true,
    "seed": false,
    "sourceStatus": {
      "xau": {
        "ok": true,
        "label": "Twelve Data XAU/USD",
        "detail": "latest daily bar 2026-09-29",
        "timestamp": "2026-09-29T10:34:00+08:00"
      },
      "dxy": {
        "ok": false,
        "label": "Twelve Data DXY",
        "detail": "No exact/confirmed DXY symbol found",
        "timestamp": "2026-09-29T10:34:00+08:00"
      },
      "brent": {
        "ok": false,
        "label": "Twelve Data Brent",
        "detail": "404 Client Error: Not Found for url: https://api.twelvedata.com/time_series?symbol=XBR%2FUSD&interval=1day&outputsize=3&order=DESC&timezone=UTC&apikey=[REDACTED]",
        "timestamp": "2026-09-29T10:34:08+08:00"
      },
      "us10y": {
        "ok": true,
        "label": "FRED DGS10",
        "detail": "latest 2026-09-25",
        "timestamp": "2026-09-29T10:34:09+08:00"
      },
      "news": {
        "ok": true,
        "label": "NewsAPI",
        "detail": "2 relevant recent items",
        "timestamp": "2026-09-29T10:34:09+08:00"
      },
      "fedSpeeches": {
        "ok": true,
        "label": "Federal Reserve speeches",
        "detail": "6 official listings",
        "timestamp": "2026-09-29T10:34:09+08:00"
      }
    },
    "warnings": [
      "DXY unavailable; dashboard shows — rather than substituting an unverified dollar index.",
      "Brent unavailable for this run."
    ]
  },
  "updated": "2026-09-29 10:34 MYT",
  "session": "Daily verified snapshot · sourced data + labelled heuristic overlays",
  "price": {
    "spot": 4137.01,
    "change": 21.93,
    "changePct": 0.53,
    "dayRange": "4,112.09 - 4,137.29",
    "monthPct": -5.03,
    "yearPct": -4.13,
    "ath": null,
    "note": "Latest provider daily bar: 2026-09-29; rolling history used: 370 bars",
    "latestDailyClose": 4137.01,
    "priceType": "DAILY_CLOSE",
    "rollingHigh": 5597.23,
    "rollingWindowBars": 370,
    "providerBarTime": "2026-09-29"
  },
  "macro": [
    {
      "label": "DXY",
      "value": "—",
      "delta": "unavailable",
      "tone": "",
      "note": "Provider symbol not confirmed"
    },
    {
      "label": "US 10Y",
      "value": "5.170%",
      "delta": "-1.0 bp",
      "tone": "good",
      "note": "FRED DGS10 · 2026-09-25"
    },
    {
      "label": "Brent",
      "value": "—",
      "delta": "unavailable",
      "tone": "",
      "note": "Provider symbol not confirmed"
    }
  ],
  "sentiment": {
    "bias": "MIXED",
    "goldTone": "NEUTRAL",
    "score": 0.133,
    "confidence": 69,
    "summary": "Mechanical daily pressure model using sourced USD/yield moves plus a small observed XAU-momentum term. It is not a forecast or trade instruction.",
    "netSpeechSignal": "NEUTRAL",
    "netSpeechPct": 0.0,
    "netNote": "Direction only. No fabricated percentage impact is assigned to headlines or speeches."
  },
  "model": {
    "base": 0.0,
    "formula": "dailyPressure = weighted(ΔDXY, ΔUS10Y, observed ΔXAU)",
    "note": "Transparent heuristic over sourced daily data. No headline/speech percentage impact is fabricated.",
    "weights": [
      {
        "k": "DXY daily move",
        "v": 0.45
      },
      {
        "k": "US 10Y daily move",
        "v": 0.45
      },
      {
        "k": "Observed XAU momentum",
        "v": 0.1
      }
    ],
    "strength": [
      {
        "k": "Source available",
        "v": 1.0
      },
      {
        "k": "Source unavailable",
        "v": 0.0
      }
    ],
    "surprise": [
      {
        "k": "Not auto-estimated",
        "v": 0.0
      }
    ]
  },
  "news": [
    {
      "time": "2026-09-28 02:01 UTC",
      "title": "PRECIOUS-Fed tightening bets weigh on gold prices",
      "summary": "Gold prices have taken a hit, influenced by rising oil rates that have sparked inflation fears and suggested further interest rate hikes may be on the horizon. Spot gold decreased by 0.7%, with US gold futures mirroring the trend. Analysts warned that escalat…",
      "source": "The Times of India",
      "url": "https://economictimes.indiatimes.com/markets/commodities/news/precious-fed-tightening-bets-weigh-on-gold-prices/articleshow/134529772.cms",
      "impact": "bearish",
      "signal": "DOWN",
      "impactPct": null
    },
    {
      "time": "2026-09-28 01:30 UTC",
      "title": "Gold Falls on Expectations of Higher for Longer Fed Rates",
      "summary": "Gold fell. Higher oil prices and strong U.S. industrial activity data reinforced expectations that the U.S. Federal Reserve may need to keep policy tighter for longer, ANZ said.",
      "source": "Biztoc.com",
      "url": "https://biztoc.com/x/00e2f545b75b0027",
      "impact": "neutral",
      "signal": "NEUTRAL",
      "impactPct": null
    }
  ],
  "speakers": [
    {
      "name": "An Update on AI and the Economy",
      "role": "Federal Reserve speaker",
      "side": "neutral",
      "signal": "NEUTRAL",
      "quote": "An Update on AI and the Economy Governor Lisa D. Cook At the Oakland Tech Week Opening Keynote, cohosted by the Kapor Center, Oakland, California",
      "impact": "Official Fed speech listing; stance is not automatically inferred.",
      "date": "2026",
      "source": "Federal Reserve",
      "url": "https://www.federalreserve.gov/newsevents/speech/cook20260928a.htm",
      "w": 0.0,
      "s": 0.0,
      "f": 0.0,
      "impactPct": 0.0
    },
    {
      "name": "A Long-Term View on the Costs of Shelter",
      "role": "Federal Reserve speaker",
      "side": "neutral",
      "signal": "NEUTRAL",
      "quote": "A Long-Term View on the Costs of Shelter Watch Live Governor Michael S. Barr At âHousing Affordability 2026: A Community Development Summit,â hosted by the Federal Reserve Bank of Chicago, Chicago, Illinois",
      "impact": "Official Fed speech listing; stance is not automatically inferred.",
      "date": "2026",
      "source": "Federal Reserve",
      "url": "https://www.federalreserve.gov/newsevents/speech/barr20260923a.htm",
      "w": 0.0,
      "s": 0.0,
      "f": 0.0,
      "impactPct": 0.0
    },
    {
      "name": "Discount Window Modernization and Treasury Market Functioning",
      "role": "Federal Reserve speaker",
      "side": "neutral",
      "signal": "NEUTRAL",
      "quote": "Discount Window Modernization and Treasury Market Functioning Watch Live Vice Chair Philip N. Jefferson At the 2026 U.S. Treasury Market Conference, Federal Reserve Bank of New York, New York, New York",
      "impact": "Official Fed speech listing; stance is not automatically inferred.",
      "date": "2026",
      "source": "Federal Reserve",
      "url": "https://www.federalreserve.gov/newsevents/speech/jefferson20260922a.htm",
      "w": 0.0,
      "s": 0.0,
      "f": 0.0,
      "impactPct": 0.0
    },
    {
      "name": "Initial Findings from Independent Review of Silicon Valley Bank",
      "role": "Federal Reserve speaker",
      "side": "neutral",
      "signal": "NEUTRAL",
      "quote": "Initial Findings from Independent Review of Silicon Valley Bank Watch Live Vice Chair for Supervision Michelle W. Bowman At the Luncheon of the Lord Mayor City of London at Mansion House, London, United Kingdom",
      "impact": "Official Fed speech listing; stance is not automatically inferred.",
      "date": "2026",
      "source": "Federal Reserve",
      "url": "https://www.federalreserve.gov/newsevents/speech/bowman20260918b.htm",
      "w": 0.0,
      "s": 0.0,
      "f": 0.0,
      "impactPct": 0.0
    },
    {
      "name": "The Final Chapter on Modernizing Bank Regulatory Stress Testing",
      "role": "Federal Reserve speaker",
      "side": "neutral",
      "signal": "NEUTRAL",
      "quote": "The Final Chapter on Modernizing Bank Regulatory Stress Testing Watch Live Vice Chair for Supervision Michelle W. Bowman At the Luncheon of the Lord Mayor City of London at Mansion House, London, United Kingdom",
      "impact": "Official Fed speech listing; stance is not automatically inferred.",
      "date": "2026",
      "source": "Federal Reserve",
      "url": "https://www.federalreserve.gov/newsevents/speech/bowman20260918a.htm",
      "w": 0.0,
      "s": 0.0,
      "f": 0.0,
      "impactPct": 0.0
    },
    {
      "name": "The Economic Outlook and Some Comments on My Policy Communication",
      "role": "Federal Reserve speaker",
      "side": "neutral",
      "signal": "NEUTRAL",
      "quote": "The Economic Outlook and Some Comments on My Policy Communication Watch Live Governor Christopher J. Waller At Reuters NEXT Newsmaker Interview, Washington, D.C.",
      "impact": "Official Fed speech listing; stance is not automatically inferred.",
      "date": "2026",
      "source": "Federal Reserve",
      "url": "https://www.federalreserve.gov/newsevents/speech/waller20260903a.htm",
      "w": 0.0,
      "s": 0.0,
      "f": 0.0,
      "impactPct": 0.0
    }
  ],
  "levels": {
    "resistance": [
      4231.05,
      4347.03,
      4406.66,
      4430.46
    ],
    "support": [
      4111.8,
      4055.45,
      3995.82,
      3879.84
    ],
    "note": "Classic pivot levels from previous daily OHLC plus recent 20-day extreme; mechanical, not guarantees."
  },
  "calendar": [],
  "pressure": [
    {
      "label": "US 10Y daily move",
      "level": "-1.0 bp",
      "w": 8,
      "dir": "up"
    },
    {
      "label": "Observed XAU momentum",
      "level": "+0.53%",
      "w": 35,
      "dir": "up"
    }
  ],
  "priceSeries": {
    "label": "XAU/USD daily close (Twelve Data)",
    "unit": "USD / troy oz",
    "yMin": 4083.27,
    "yMax": 4411.94,
    "points": [
      {
        "x": "2026-09-16",
        "y": 4264.07
      },
      {
        "x": "2026-09-17",
        "y": 4341.9
      },
      {
        "x": "2026-09-18",
        "y": 4377.25
      },
      {
        "x": "2026-09-19",
        "y": 4380.13
      },
      {
        "x": "2026-09-20",
        "y": 4380.13
      },
      {
        "x": "2026-09-21",
        "y": 4343.81
      },
      {
        "x": "2026-09-22",
        "y": 4357.68
      },
      {
        "x": "2026-09-23",
        "y": 4286.97
      },
      {
        "x": "2026-09-24",
        "y": 4275.28
      },
      {
        "x": "2026-09-25",
        "y": 4286.74
      },
      {
        "x": "2026-09-26",
        "y": 4286.21
      },
      {
        "x": "2026-09-27",
        "y": 4286.21
      },
      {
        "x": "2026-09-28",
        "y": 4115.08
      },
      {
        "x": "2026-09-29",
        "y": 4137.01
      }
    ]
  },
  "macroSeries": {
    "label": "DXY unavailable",
    "unit": "index",
    "yMin": 0,
    "yMax": 1,
    "points": [
      {
        "x": "2026-09-29",
        "y": 0
      }
    ]
  },
  "oddsSeries": {
    "label": "DXY unavailable",
    "unit": "index",
    "yMin": 0,
    "yMax": 1,
    "points": [
      {
        "x": "2026-09-29",
        "y": 0
      }
    ]
  },
  "sources": [
    "Twelve Data — XAU/USD daily market data",
    "Federal Reserve — official speech listings",
    "FRED — DGS10 US 10-Year Treasury Constant Maturity Rate",
    "NewsAPI — recent gold/macro headlines"
  ]
};
